# 10 Constrastes de Independencia

Dado $n$ individuos se clasifican según dos criterios $(X,Y)$. Sean $x_1,\ldots, x_I$ los distintos niveles del criterio $X$ y sean $y_1,\ldots, y_J$ los distintos niveles del criterio $Y$.

$\textbf{Ejemplo}$ Supongamos que tenemos una tabla de contingencia que muestra la relación entre el nivel educativo y el sector de empleo de una muestra de personas. Queremos determinar si el nivel educativo y el sector de empleo están independientemente relacionados.

In [1]:
import numpy as np
import pandas as pd

datos = {'Nivel educativo': np.repeat(np.array(['Secundaria', 'Preparatoria', 'Universidad']), (60, 75, 55)),
         'Sector de empleo': np.repeat(np.array(['Independiente','Privado', 'Público', 
                                                 'Independiente','Privado', 'Público', 
                                                 'Independiente','Privado', 'Público']), (15, 25, 20, 25, 20, 30, 10, 15, 30))
        }
df = pd.DataFrame(datos)

tabla_contingencia1 = pd.crosstab(df['Nivel educativo'], df['Sector de empleo'], margins=True)

tabla_contingencia1

Sector de empleo  Independiente  Privado  Público  All
Nivel educativo
Preparatoria                 25       20       30   75
Secundaria                   15       25       20   60
Universidad                  10       15       30   55
All                          50       60       80  190

$\textbf{Ejemplo}$ En un estudio de una vacuna de hepatitis participan 1083 voluntarios. De éstos, se eligen aleatoriamente 549 y son vacunados. Los otros, 534, no son vacunados. Después de un cierto tiempo, se observa que 70 de los 534 no vacunados han contraído la hepatitis, mientras que sólo 11 de los 549 vacunados la han contraído.

In [2]:
datos = {'Sintomas': np.repeat(np.array(['Si', 'No']), (81, 1002)),
         'Vacuna': np.repeat(np.array(['Con','Sin', 'Con','Sin']), (11, 70, 538, 464))
        }
df = pd.DataFrame(datos)

tabla_contingencia2 = pd.crosstab(df['Sintomas'], df['Vacuna'], margins=True)
tabla_contingencia2

Vacuna    Con  Sin   All
Sintomas
No        538  464  1002
Si         11   70    81
All       549  534  1083

Así, definimos $n_{ij}$ como el número de individuos clasificados en el nivel $x_i$ según el criterio $X$ y clasificados en el nivel $y_j$ según el criterio $Y$. A partir de dichos valores construimos la denominada tabla de contingencia:

<img src=tablacon.png>

En la tabla anterior, $n_{i∙}$ sería el número total de individuos clasificados en el nivel $x_i$ según el criterio $X$ y  $n_{∙j}$ el número total de individuos clasificados en el nivel $y_j$ según el criterio  $Y$.

De este modo las hipótesis serían las siguientes:

$H_0:$ Los criterios de clasificación $X$ y $Y$ son independientes,

$H_1:$ Los criterios de clasificación $X$ y $Y$ son dependientes,

Modelando el problema anterior como un test de bondad de ajuste se tendría que considerar una nueva variable $Z=(X,Y)$, denominada variable modelo, cuyo dominio es $\{(x_1,y_1), ..., (x_I, y_J)\}$.

Bajo la hipótesis $H_0$ se tiene que la distribución de $Z$ es:

<img src=probconj.png>

El estadístico asociado es:

<img src=chi-cuad.png>

el cual sigue aproximadamente una distribución $\chi^2$ con (I-1)(J-1) grados de libertad.

En la biblioteca scipy.stats contiene la función chi2_contingency para realizar estas operaciones.

In [3]:
from scipy.stats import chi2_contingency

chi2_contingency(tabla_contingencia1)

Chi2ContingencyResult(statistic=8.852272727272728, pvalue=0.4510210999594174, dof=9, expected_freq=array([[ 19.73684211,  23.68421053,  31.57894737,  75.        ],
       [ 15.78947368,  18.94736842,  25.26315789,  60.        ],
       [ 14.47368421,  17.36842105,  23.15789474,  55.        ],
       [ 50.        ,  60.        ,  80.        , 190.        ]]))

Conclusión: No se rechaza la hipótesis nula.
No hay suficiente evidencia para afirmar que el nivel educativo y el sector de empleo son independientes.

In [4]:
chi2_contingency(tabla_contingencia2)

Chi2ContingencyResult(statistic=48.24187670221911, pvalue=8.40321419124006e-10, dof=4, expected_freq=array([[ 507.93905817,  494.06094183, 1002.        ],
       [  41.06094183,   39.93905817,   81.        ],
       [ 549.        ,  534.        , 1083.        ]]))

Conclusión: Se rechaza la hipótesis nula.

### Ejercicio: Supongamos que los registros de la muestra proporcionan el siguiente resultado de las ventas de tres productos en 4 regiones; queremos saber si las regiones representan un cambio significativo en las ventas.

<img src=Tabla1.png>